//
// Created by Henryk Wollik on 07/06/15.
//

#include "glfwConsts.h"
#include "../utils/utils.h"
#include <GLFW/glfw3.h>

#define _(name) EXPORT_SET_CONST(#name,GLFW_ ## name)

void glfwConsts::init(Handle<Object> exports) {
    _(KEY_UNKNOWN);
    _(KEY_SPACE);
    _(KEY_APOSTROPHE);
    _(KEY_COMMA);
    _(KEY_MINUS);
    _(KEY_PERIOD);
    _(KEY_SLASH);
    _(KEY_0);
    _(KEY_1);
    _(KEY_2);
    _(KEY_3);
    _(KEY_4);
    _(KEY_5);
    _(KEY_6);
    _(KEY_7);
    _(KEY_8);
    _(KEY_9);
    _(KEY_SEMICOLON);
    _(KEY_EQUAL);
    _(KEY_A);
    _(KEY_B);
    _(KEY_C);
    _(KEY_D);
    _(KEY_E);
    _(KEY_F);
    _(KEY_G);
    _(KEY_H);
    _(KEY_I);
    _(KEY_J);
    _(KEY_K);
    _(KEY_L);
    _(KEY_M);
    _(KEY_N);
    _(KEY_O);
    _(KEY_P);
    _(KEY_Q);
    _(KEY_R);
    _(KEY_S);
    _(KEY_T);
    _(KEY_U);
    _(KEY_V);
    _(KEY_W);
    _(KEY_X);
    _(KEY_Y);
    _(KEY_Z);
    _(KEY_LEFT_BRACKET);
    _(KEY_BACKSLASH);
    _(KEY_RIGHT_BRACKET);
    _(KEY_GRAVE_ACCENT);
    _(KEY_WORLD_1);
    _(KEY_WORLD_2);
    _(KEY_ESCAPE);
    _(KEY_ENTER);
    _(KEY_TAB);
    _(KEY_BACKSPACE);
    _(KEY_INSERT);
    _(KEY_DELETE);
    _(KEY_RIGHT);
    _(KEY_LEFT);
    _(KEY_DOWN);
    _(KEY_UP);
    _(KEY_PAGE_UP);
    _(KEY_PAGE_DOWN);
    _(KEY_HOME);
    _(KEY_END);
    _(KEY_CAPS_LOCK);
    _(KEY_SCROLL_LOCK);
    _(KEY_NUM_LOCK);
    _(KEY_PRINT_SCREEN);
    _(KEY_PAUSE);
    _(KEY_F1);
    _(KEY_F2);
    _(KEY_F3);
    _(KEY_F4);
    _(KEY_F5);
    _(KEY_F6);
    _(KEY_F7);
    _(KEY_F8);
    _(KEY_F9);
    _(KEY_F10);
    _(KEY_F11);
    _(KEY_F12);
    _(KEY_F13);
    _(KEY_F14);
    _(KEY_F15);
    _(KEY_F16);
    _(KEY_F17);
    _(KEY_F18);
    _(KEY_F19);
    _(KEY_F20);
    _(KEY_F21);
    _(KEY_F22);
    _(KEY_F23);
    _(KEY_F24);
    _(KEY_F25);
    _(KEY_KP_0);
    _(KEY_KP_1);
    _(KEY_KP_2);
    _(KEY_KP_3);
    _(KEY_KP_4);
    _(KEY_KP_5);
    _(KEY_KP_6);
    _(KEY_KP_7);
    _(KEY_KP_8);
    _(KEY_KP_9);
    _(KEY_KP_DECIMAL);
    _(KEY_KP_DIVIDE);
    _(KEY_KP_MULTIPLY);
    _(KEY_KP_SUBTRACT);
    _(KEY_KP_ADD);
    _(KEY_KP_ENTER);
    _(KEY_KP_EQUAL);
    _(KEY_LEFT_SHIFT);
    _(KEY_LEFT_CONTROL);
    _(KEY_LEFT_ALT);
    _(KEY_LEFT_SUPER);
    _(KEY_RIGHT_SHIFT);
    _(KEY_RIGHT_CONTROL);
    _(KEY_RIGHT_ALT);
    _(KEY_RIGHT_SUPER);
    _(KEY_MENU);
    _(KEY_LAST);

    _(MOD_SHIFT);
    _(MOD_CONTROL);
    _(MOD_ALT);
    _(MOD_SUPER);
}
